"""create event_days and attendances tables

Revision ID: 0e5788fa6e33
Revises: 452e72704eff
Create Date: 2025-05-16 19:23:31.357511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e5788fa6e33'
down_revision: Union[str, None] = '452e72704eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendees_email', table_name='attendees')
    op.drop_index('ix_attendees_id', table_name='attendees')
    op.drop_table('attendees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('attendee', 'speaker', 'organizer', name='roleenum'), autoincrement=False, nullable=True),
    sa.Column('rfid_uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registered', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('got_kit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('got_lunch', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='attendees_pkey'),
    sa.UniqueConstraint('rfid_uid', name='attendees_rfid_uid_key')
    )
    op.create_index('ix_attendees_id', 'attendees', ['id'], unique=False)
    op.create_index('ix_attendees_email', 'attendees', ['email'], unique=True)
    # ### end Alembic commands ###
