"""add updated_at column to attendees

Revision ID: dd98988996fd
Revises: dba113e0480a
Create Date: 2025-05-16 18:28:00.887364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd98988996fd'
down_revision: Union[str, None] = 'dba113e0480a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendees', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendees', 'updated_at')
    # ### end Alembic commands ###
